# Wicci Project; module makefile; requires GNU Make.
# Copyright (c) 2005-2009, J. Greg Davidson.
# You may use this file under the terms of the
# GNU AFFERO GENERAL PUBLIC LICENSE 3.0
# as specified in the file LICENSE.md included with this distribution.
# All other use requires my permission in writing.
include ../TorName/Makefile.tor-name
TOR_ENV_H := $(TOR_NAME_H)
TOR_ENV_VPATH_H := $(TOR_NAME_VPATH_H) $(Core)/TorEnv
TOR_ENV_INC := $(TOR_NAME_INC) -I$(Core)/TorEnv
