# Wicci Project; module makefile; requires GNU Make.
# Copyright (c) 2005-2009, J. Greg Davidson.
# You may use this file under the terms of the
# GNU AFFERO GENERAL PUBLIC LICENSE 3.0
# as specified in the file LICENSE.md included with this distribution.
# All other use requires my permission in writing.
#include ../Tor/Makefile.tor
#TOR_NAME_H := $(TOR_H) 
#TOR_NAME_VPATH_H := $(TOR_VPATH_H) $(Core)/TorName
#TOR_NAME_INC := $(TOR_INC) -I$(Core)/TorName
